l=k

diff --git a/.github/workflows/validate-report.yml b/.github/workflows/validate-report.yml
--- a/.github/workflows/validate-report.yml
+++ b/.github/workflows/validate-report.yml
@@ -33,24 +33,32 @@ jobs:
       # -------------------------------
       # Run Salesforce Code Analyzer
       # -------------------------------
-      - name: Run Salesforce Code Analyzer
-        run: |
-          sf code-analyzer run \
-            --workspace . \
-            --target force-app/main/default \
-            --view detail \
-            --output-file sfca_results.sarif \
+      # - name: Run Salesforce Code Analyzer
+      #   run: |
+      #     sf code-analyzer run \
+      #       --workspace . \
+      #       --target force-app/main/default \
+      #       --view detail \
+      #       --output-file sfca_results.sarif \
+      #       --output-file sfca_results.html
+      - name: Run Salesforce Code Analyzer (changed files only)
+        uses: forcedotcom/run-code-analyzer@v2
+        with:
+          run-arguments: >
+            --target  force-app/main/default \
+            --view detail
             --output-file sfca_results.html
-
+          results-artifact-name: salesforce-code-analyzer-results
+          github-token: ${{ github.token }}
 
       # -------------------------------
       # Fail if ANY violations exist
       # -------------------------------
-      - name: Fail job if violations exist
-        run: |
-          jq -e '[.runs // [] | .[].results // []] | flatten | length > 0' sfca_results.sarif \
-          && exit 1 \
-          || echo "✅ No violations found"
+      # - name: Fail job if violations exist
+      #   run: |
+      #     jq -e '[.runs // [] | .[].results // []] | flatten | length > 0' sfca_results.sarif \
+      #     && exit 1 \
+      #     || echo "✅ No violations found"
 
 
       # -------------------------------
