upadte

diff --git a/.github/workflows/validate-report.yml b/.github/workflows/validate-report.yml
--- a/.github/workflows/validate-report.yml
+++ b/.github/workflows/validate-report.yml
@@ -32,17 +32,14 @@ jobs:
       # -------------------------------
       - name: Get changed files
         run: |
-          # Fetch base branch
           git fetch origin ${{ github.base_ref }}
 
-          # Get changed files under force-app/main/default
           CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD \
             | grep '^force-app/main/default/' || true)
 
           echo "Changed files:"
           echo "$CHANGED_FILES"
 
-          # Convert to space-separated list
           CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ' | sed 's/ $//')
 
           echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
@@ -63,10 +60,11 @@ jobs:
           github-token: ${{ github.token }}
 
       # -------------------------------
-      # Fail if ANY violations exist
-      # -------------------------------
-       - name: Fail job if violations exist
-         run: |
-           jq -e '[.runs // [] | .[].results // []] | flatten | length > 0' sfca_results.sarif \
-           && exit 1 \
-           || echo "✅ No violations found"
+      # Fail if ANY violations exist
+      # -------------------------------
+      - name: Fail job if violations exist
+        if: ${{ env.CHANGED_FILES != '' }}
+        run: |
+          jq -e '[.runs[]?.results[]?] | length > 0' sfca_results.sarif \
+          && exit 1 \
+          || echo "✅ No violations found"
